# Generated by Django 4.1.1 on 2022-09-17 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField(blank=True, null=True)),
                ('offered_salary', models.CharField(blank=True, max_length=50)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='media/jobs/default.png', upload_to='media/jobs')),
                ('type', models.CharField(choices=[('1', 'Full Time'), ('2', 'Part Time'), ('3', 'Freelance'), ('4', 'Temporary')], default='1', max_length=1)),
                ('gender', models.CharField(choices=[('1', 'Both'), ('2', 'Male'), ('3', 'Female')], default='1', max_length=1)),
                ('career_level', models.CharField(choices=[('1', 'Entry-level'), ('2', 'Intermediate'), ('3', 'Mid-level'), ('4', 'Senior'), ('5', 'Manager')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
    ]
