# Generated by Django 4.1.1 on 2022-10-05 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('candidates', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='career_level',
            field=models.CharField(choices=[('1', 'Entry-level'), ('2', 'Intermediate'), ('3', 'Mid-level'), ('4', 'Senior'), ('5', 'Manager')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('1', 'Both'), ('2', 'Male'), ('3', 'Female')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='offered_salary',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('1', 'Full Time'), ('2', 'Part Time'), ('3', 'Freelance'), ('4', 'Temporary')], default='1', max_length=1),
        ),
    ]
